# Generated by Django 5.2.3 on 2025-06-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("double", "Double"),
                            ("suite", "Suite"),
                            ("deluxe", "Deluxe"),
                            ("family", "Family"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("premium", "Premium"),
                            ("standard", "Standard"),
                            ("basic", "Basic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("number_of_beds", models.IntegerField(default=1)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="room_images/"),
                ),
                (
                    "amenities",
                    models.TextField(
                        help_text="Comma-separated list of amenities (e.g. WiFi, TV, AC, etc.)"
                    ),
                ),
                ("room_number", models.CharField(max_length=10, unique=True)),
                ("floor", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
