# Generated by Django 5.2.1 on 2025-06-15 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_newsletter_newslettersubscription_retreat_service_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="testimonial_images/"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Newsletter",
        ),
        migrations.RemoveField(
            model_name="retreatbooking",
            name="retreat",
        ),
        migrations.RemoveField(
            model_name="retreatbooking",
            name="room_booking",
        ),
        migrations.RemoveField(
            model_name="retreatbooking",
            name="user",
        ),
        migrations.AlterField(
            model_name="booking",
            name="number_of_guests",
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name="Retreat",
        ),
        migrations.DeleteModel(
            name="RetreatBooking",
        ),
    ]
