# Generated by Django 5.2.1 on 2025-06-15 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_testimonial_delete_newsletter_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guest_email",
            field=models.EmailField(default="guest@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_name",
            field=models.CharField(default="Guest", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_phone",
            field=models.CharField(default="N/A", max_length=20),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
